language: scala
scala:
   - 2.11.11
   - 2.12.3
jdk:
   - oraclejdk8
cache:
  directories:
    - $HOME/.ivy2
    - $HOME/.sbt
script:
  - "sbt clean coverage test"
after_success: "sbt coverageReport coveralls"
